# Generated by Django 2.2 on 2020-01-13 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
            ],
            options={
                'db_table': 'mcjz_department',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255, unique=True)),
                ('start_timer', models.DateField(auto_now_add=True)),
                ('overtime', models.CharField(max_length=30)),
                ('note', models.TextField()),
            ],
            options={
                'db_table': 'mcjz_project',
            },
        ),
        migrations.CreateModel(
            name='WorkerInfo',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('worker', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=30, unique=True)),
                ('phone_nmber', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=1)),
                ('entry_data', models.DateField(auto_now_add=True)),
                ('leave_data', models.DateField(null=True)),
                ('das_salary', models.IntegerField()),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='info_project_id', to='db.Project')),
            ],
            options={
                'db_table': 'mcjz_worker_info',
            },
        ),
        migrations.CreateModel(
            name='WorkerType',
            fields=[
                ('worker_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=125)),
            ],
            options={
                'db_table': 'mcjz_worker_type',
            },
        ),
        migrations.CreateModel(
            name='WorkerInfoChange',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_date', models.DateField(auto_now_add=True)),
                ('column', models.CharField(max_length=30)),
                ('data_date', models.DateField()),
                ('manager', models.CharField(max_length=30)),
                ('original_data', models.CharField(max_length=200)),
                ('change_data', models.CharField(max_length=200)),
                ('note', models.TextField()),
                ('worker_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_change_worker_id', to='db.WorkerInfo')),
            ],
            options={
                'db_table': 'mcjz_worker_change',
            },
        ),
        migrations.AddField(
            model_name='workerinfo',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='info_worker_type_id', to='db.WorkerType'),
        ),
        migrations.CreateModel(
            name='WorkerHoursChange',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_date', models.DateField(auto_now_add=True)),
                ('column', models.CharField(max_length=30)),
                ('data_date', models.DateField()),
                ('manager', models.CharField(max_length=30)),
                ('original_data', models.CharField(max_length=200)),
                ('change_data', models.CharField(max_length=200)),
                ('note', models.TextField()),
                ('worker_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_worker_id', to='db.WorkerInfo')),
            ],
            options={
                'db_table': 'mcjz_hours_change',
            },
        ),
        migrations.CreateModel(
            name='WorkerHours',
            fields=[
                ('working_hours_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_data', models.DateField(auto_now=True)),
                ('writer', models.CharField(max_length=30)),
                ('pname', models.CharField(max_length=100)),
                ('work_day', models.DecimalField(decimal_places=2, max_digits=16)),
                ('overtime', models.DecimalField(decimal_places=2, max_digits=16)),
                ('day_salary', models.DecimalField(decimal_places=2, max_digits=16)),
                ('over_salary', models.DecimalField(decimal_places=2, max_digits=16)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=16)),
                ('note', models.TextField()),
                ('worker_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_hours_worker_id', to='db.WorkerInfo')),
            ],
            options={
                'db_table': 'mcjz_worker_hours',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=125)),
                ('id_card', models.CharField(max_length=18)),
                ('telephone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=125)),
                ('icon', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_department_id', to='db.Department')),
            ],
            options={
                'db_table': 'mcjz_staff',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_staff_id', to='db.Staff'),
        ),
    ]
