# Generated by Django 2.2 on 2020-01-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20200115_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerinfo',
            name='id_number',
            field=models.CharField(max_length=30),
        ),
    ]
