# Generated by Django 2.2 on 2020-01-16 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20200115_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerhours',
            old_name='entry_data',
            new_name='write_data',
        ),
    ]
