# Generated by Django 2.2 on 2020-01-17 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20200116_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveRecode',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_date', models.DateField(auto_now_add=True)),
                ('column', models.CharField(max_length=30)),
                ('data_date', models.DateField()),
                ('manager', models.CharField(max_length=30)),
                ('original_data', models.CharField(max_length=200)),
                ('change_data', models.CharField(max_length=200)),
                ('note', models.TextField()),
                ('status', models.IntegerField(default=1)),
                ('approver', models.CharField(max_length=30)),
                ('approver_note', models.TextField()),
                ('worker_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_change_worker_id', to='db.WorkerInfo')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkerInfoChange',
        ),
    ]
