# Generated by Django 2.2 on 2020-01-17 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20200117_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approverecode',
            old_name='approve_submit_date',
            new_name='submit_date',
        ),
    ]
