# Generated by Django 2.2 on 2020-01-18 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_auto_20200117_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='approverecode',
            name='working_hours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_hours', to='db.WorkerHours'),
        ),
        migrations.AlterField(
            model_name='approverecode',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
