# Generated by Django 2.2 on 2020-01-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_workerhourschange_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerhourschange',
            name='approver',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workerhourschange',
            name='approver_note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workerhourschange',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
